spring.application.name=mycoolapp

#exposing other actuators like /info,/beans,etc
management.endpoints.web.exposure.include=*
management.info.env.enabled=true

#Customized /actuator/info
info.app.name="My cool All"
info.app.description = "It is damn Cool"

cartoon.name="Shin chan"

#changing default port

server.port=7070

#adding context path
server.servlet.context-path=/mycoolapp